-- CLONE FEATURE IN SNOWFLAKE.

SELECT * FROM EMP 

SELECT * FROM EMP WHERE FIRST_NAME='Arlene'; 

DELETE FROM EMP WHERE FIRST_NAME='Violette'

-- CLONE TABLE

CREATE OR REPLACE TRANSIENT TABLE EMP_CLONE CLONE EMP

SELECT * FROM EMP_CLONE

-- Make changes in EMP_CLONE it should not affect EMP Table.

DELETE FROM EMP_CLONE WHERE FIRST_NAME='Arlene';

SELECT * FROM EMP_CLONE WHERE FIRST_NAME='Violette';

SELECT * FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS WHERE TABLE_NAME LIKE 'EMP'
AND TABLE_CATALOG='SFNOWFLAKE_TUTORIAL' AND TABLE_DROPPED IS NULL

SELECT * FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS WHERE TABLE_NAME LIKE 'EMP_CLONE'
AND TABLE_CATALOG='SFNOWFLAKE_TUTORIAL' AND TABLE_DROPPED IS NULL
