ALTER DATABASE READER_SALES SET DATA_RETENTION_TIME_IN_DAYS=0

CREATE OR REPLACE TABLE READER_SALES.PUBLIC.CUSTOMER
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER;

CREATE OR REPLACE TRANSIENT TABLE READER_SALES.PUBLIC.CUSTOMER
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER;


CREATE OR REPLACE TEMPORARY TABLE READER_SALES.PUBLIC.CUSTOMER_TEMP
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER;



SELECT * FROM READER_SALES.PUBLIC.CUSTOMER_TEMP LIMIT 100

CREATE OR REPLACE TRANSIENT TABLE READER_SALES.PUBLIC.CUSTOMER
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER;

SHOW TABLES

DROP TABLE READER_SALES.PUBLIC.CUSTOMER

UNDROP TABLE READER_SALES.PUBLIC.CUSTOMER

select *
  from sales.information_schema.table_storage_metrics
  -- where table_catalog = 'SALES';
